### ISSUE TITLE
Need big amount of Koran ETH

### ISSUE THREAD

**Issue by KorzhikDM** [kovan-testnet/faucet#36]
Hi!

We've just finished our main functionality of our DApp(demo.rocketdao.io). And we are in process of preparing big bounty testing now. In this case we want to give all users who want to test our DApp  about 20 kETH per user. We expect about 1000 - 5000 users during month. So we need 20 000 kETH - 100 000 kETH
Is it possible to get or buy such amount?

**Comment by ddorgan** [comment]
Why do they need 20 keth ? What's the gas price of a transaction on your platform? 

Also if it's for staking in a DAO, then letting all users have .2 keth or 20 keth is the exact same from the end user point of view.

**Comment by KorzhikDM** [comment]
We want to simulate activity of Rocket DAO and do high tests. Minimum decentralized fund size on platform is 5ETH.
So we expect that users will create each fund with size 50ETH and more. Moreover we want to give  users opportunity to participate in different funds that's why we want to give each user 20 kETH

**Comment by ddorgan** [comment]
I think you're missing my point. Why would a user need 5ETH? If every user gets the same amount, then .5 eth would basically be the same as 5eth (DAO wise) and it would mean giving out a lot less tokens which could be used to attack the network.

**Comment by KorzhikDM** [comment]
No. I'm not missing you. Maybe I need describe Rocket DAO. 
Smart contracts have given a possibility to create decentralized investment funds. Most vivid example of decentralized venture fund creation is The DAO when 20,000 people put 4,000,000 ETHs on one smart contract in order to jointly invest in new startups. 
We implement similar concept in Rocket DAO. We provide users with an opportunity to create decentralized funds using smart contracts. Minimum fund size is 5ETH. Our main users are angel investors(crypto investors). We do Rocket DAO for them. That's why we want to give them 20 kETH to simulate user experience on Rocket DAO. It's important to give them investment experience via funds on test network before they will do it on mainnet. Because DApp's are very new and unknown for final users. And we need to educate them before usage if we want to make DApp's popular among internet users.

**Comment by Tbaut** [comment]
We don't want to give away 100 000 KETH because you can very much spam the whole network and bother a lot of organizations that use it, I'm sure that's something you can understand.

>Minimum fund size is 5ETH. 

Set it to .5 and that'll work. Dapps should give the ETH equivalent in FIAT currency, this is all what investors need to bother about anyways.

**Comment by KorzhikDM** [comment]
> We don't want to give away 100 000 KETH because you can very much spam the whole network and bother a lot of organizations that use it, I'm sure that's something you can understand.

Network spam depends on how much transactions you have. Not amount of kETH. I'm right? 
We can count transactions. We will have 2 demo startups where user can invest via fund.
It's two voting transaction. We expect that user will try to create their own fund(It's one smart-contract deployment) or join to other fund on platform. Get tokens after investment. So average amount 5-10 transaction per user. We expect 1000 - 5000 users per in next 3 month.
Is it a lot? 

> Set it to .5 and that'll work. 
It's not possible. Because we are not giving user experience. Firstly we want to do customer development.

> Dapps should give the ETH equivalent in FIAT currency, this is all what investors need to bother about anyways.

It's not our business. We will integrate Coinbase or Changelly to do it.

**Comment by Tbaut** [comment]
>Network spam depends on how much transactions you have. Not amount of kETH.

No. There is a direct relation between the 2. If you have a lot of KETH you can send a lot of Txs, thus spam the network.

>It's two voting transaction. We expect that user will try to create their own fund(It's one smart-contract deployment) or join to other fund on platform. Get tokens after investment. So average amount 5-10 transaction per user.

Yeah, so what you need is a lot less than what you ask. For a typical contract transaction requiring 100k gas at a price of 20 Gwei (high gas cost, this would also work with 10x less as it's Kovan), you can make: 0.5e18 / (100000 * 20e9) = 250 transactions with just 0.5 KEth !!

Even sending you 10 000KETH would be *a lot* as all we are talking about the upper limit of an approximation, in 3 months. 

Don't get us wrong, our problem is not to give away free KETH to projects that want to use Kovan. Our problem is giving a lot of ETH, because if they end up in malicious hands,  they can bother all the other projects out there that use Kovan. 

What about sending you 5 000 KETH right now, and feel free to come back again when you realize that the project picks up as expected and we can re-send you some in a manner of hours. As explained several times before, you should consider giving a lot less to your users as they do not need 5KETH.

**Comment by KorzhikDM** [comment]
> What about sending you 5 000 KETH right now, and feel free to come back again when you realize that the project picks up as expected and we can re-send you some in a manner of hours. As explained several times before, you should consider giving a lot less to your users as they do not need 5KETH.

It's good idea. Let's start with 5 000 KETH. We will show you progress and how we spent this KETH. And after that you will decide to give us another portion of KETH.  
0xcbea2155a147c7ecf25cad15e8c24b37e0a27511

**Comment by Tbaut** [comment]
Done https://kovan.etherscan.io/tx/0xf3418212d3c9deb975a29c09bd0d49cdf5425f14968b6f2b92b01a5915e759ca

**Comment by tonnypham94** [comment]
Could you help me to get 2000 KETH? I know its a big amount of KETH but my team have to get it to test ours code because we have to create more users. Thank you very much! @Tbaut 
My address: 0x3B8a67Ad64160e0b977B6dD877e0fB98878aB902

**Comment by Tbaut** [comment]
Parity have no more Kovan authority. Please ask here https://github.com/poanetwork
