### ISSUE TITLE
500 kETH for dApp

### ISSUE THREAD

**Issue by pseudonaut** [kovan-testnet/faucet#48]
Hello,

I'm requesting 500 kETH to test my decentralized application. The premise is that it's a fully interactive option chain for Ethereum that uses a modularized smart contract architecture, where you can view an order book of smart contracts - each collateralized with 5 ETH (for call options) and the corresponding amount of collateral for put options.

The standardized amount is 5 ETH, so testing an order book of 15 - 20 Smart Contracts would require a fairly sizable amount of kETH.

My address is 0x3E644B1E792E334EA518FA1115D5D62A70cbf5fE and my site is www.inveth.io

Best,
John

**Comment by Tbaut** [comment]
Hi,
Is your project open source? (please provide a link).

**Comment by pseudonaut** [comment]
The project is not open source currently.

Sent from Yahoo Mail on Android 
 
  On Tue, Oct 23, 2018 at 8:40 AM, Thibaut Sardan<notifications@github.com> wrote:   
Hi,
Is your project open source? (please provide a link).

**Comment by Tbaut** [comment]
Please use a lower amount of ETH for testing, the amount of Tx you can create with 500ETH represents a threats to the network. If you use .5ETH instead of 5, your user/you can still send dozens of transactions, and this will not change the load on your system- It is really sad that your project isn't open source. I sent you 50ETH https://kovan.etherscan.io/tx/0x5a070c4af6b8a68ca5c4ce09f3b0b2c6be79ac3b74bab480d419665fa5860f80
