### ISSUE TITLE
Large KETH request.

### ISSUE THREAD

**Issue by AC0DEM0NK3Y** [kovan-testnet/faucet#50]
Hi I would like to request a large drop of KETH please.

We are already on mainnet (for eg. https://mint.enjincoin.io/ plus larger full early adopters) but are edging closer to opening this up even further to the public and need to test at large volume on kovan first.
This will mean users will need KETH for their own transactions, so we are creating our own time limited faucet for this that can also send a package of our testnet utility tokens simultaneously.

If you could ideally send 1000 to 0xB0A6237D376B71AE1E480A8c728239ED663Fa941 that would be great, thankyou.

**Comment by Tbaut** [comment]
We can't provide 1000 at once as this could be a potential threat to the network.
Instead of giving your user 1 or 5KETH, you could give them .1 or .5, which doesn't make any difference from the scalability pov, and helps us prevent any attack.
I sent you 100KETH https://kovan.etherscan.io/tx/0x3b9eff6c4aff30e692b4cfc40cf78bf499650b9a9ce32c4a531a496b0e2ca2ef
