### ISSUE TITLE
1 KETH request

### ISSUE THREAD

**Issue by Remi-Tuy** [kovan-testnet/faucet#59]
Hello,

We are building a 3rd layer solution on top of Dharma protocol and Centrifuge.io Nodes called Lendflo 👍 
We have requested 50 TETH a few weeks ago, but obviously quickly ran out.
Could have have 1k ETH to finalize our development and testing of our Crowdfunding of Dharma Debt Order Collateralize by Centrifuge NFTs.

Ty :)

**Comment by Tbaut** [comment]
You had [requested 500](https://github.com/kovan-testnet/faucet/issues/52#issuecomment-436249722), and I sent you 100 because of absence of open source project preventing me to verify your sayings. It looks like the transaction didn't make it though! Sorry about that, I'm happy to send you these again. However, please understand that I will not send you 1000 KETH because if you really this represent a threat to the network. Also if you really need this much, it means there is something wrong in your tests. Please confirm the address I should send you the KETH to.

**Comment by Remi-Tuy** [comment]
I am happy to share parts of our project with you so you can confirm what I am claiming :)
I understand, 100 ETH will help out a bit, we will find a way to optimize or do more testing on a private net so less is needed.

The addresss is: 0x7a6f79dFE306a7A7abAFeCc1E7166aAeC30c20B4

**Comment by Tbaut** [comment]
Would love to get access to whatever you can give me access to :)
100 KETH sent with :heart: using [Fether](https://github.com/paritytech/fether) : https://kovan.etherscan.io/tx/0x6398fcb5c2792e26d4123e85669b0237f85223655ed9ecf481991f1060909448

**Comment by jjsage123** [comment]
Huh
