### ISSUE TITLE
Request 100 KETH for Ethereum app on Unity

### ISSUE THREAD

**Issue by kentchan23** [kovan-testnet/faucet#71]
HI,

I am doing a FYP about NETHEREUM on Unity. The purpose of this project is introducing "What is Blockchain".

I want to get 100 KETH as a wallet pool for rewarding the users who were finished the Mini games on Unity. 

My wallet address:
0x9e1508066bcc5f645201F1578A8171D7117F877F

Thank you!.

**Comment by Tbaut** [comment]
Can you link your project? is this open source?
How many users do you expect to have?

**Comment by kentchan23** [comment]
Dear Tbaut,

My project is including the open source on below link :
[https://github.com/Nethereum/Nethereum.Flappy](url)

Draft system structure shown below:
![image](https://user-images.githubusercontent.com/43563601/52952400-59ceb580-33bf-11e9-95d0-d6f086bf1415.png)

I Expected around 10 users as debuger for this project. I will use other method to deploy my project if it was approved by my supervisor. 

Thank you.

**Comment by Tbaut** [comment]
Understood, I believe that 100 ETH is a little overkill for such a use-case. You do not need to incentive your users with dozens of KETH. The reason we do not send large amounts of ETH is because it could be a threat for the network. You could for instance reward 0.5 ETH to the users. I've sent to you 20 KETH so that you can get started. https://blockscout.com/eth/kovan/tx/0x2dc01431fc523e906d6592a83b52fae1d518b596ab2faafdfdac19c1f4f49e77/internal_transactions
